version: 2.1
jobs:
  #  CHECKOUT REPOSITORY
  checkout_repo:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/oipa-query-builder
    steps:
      - checkout
      - attach_workspace:
          at: ~/oipa-query-builder
      - restore_cache:
          keys:
            - yarncache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: yarncache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./.cache
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
            - ~/.cache/Cypress

  #  BUILD SOURCE AND DEPLOY TO SERVER
  build_deploy:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/oipa-query-builder
    steps:
      - checkout
      - attach_workspace:
          at: ~/oipa-query-builder
      - run: sudo apt-get install python-dev
      - run:
          name: Set REACT_APP_PROJECT_URL env var
          command: |
            echo 'export REACT_APP_PROJECT_URL="$REACT_APP_PROJECT_URL_DEV"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Add target host to known_hosts files
          command: |
            ssh-keyscan "$SSH_HOST_DEV" >> ~/.ssh/known_hosts
      - add_ssh_keys:
          name: Add SSH KEY
          fingerprints:
            - "6c:2e:69:0b:b6:6c:33:a8:6f:29:f3:ab:f7:d2:9c:26"
      - run: eval ssh-agent -s
      - run: sudo apt install rsync
      - run:
          name: Upload build folder to target host
          command: |
            rsync -O -ave ssh ~/oipa-query-builder/build "$SSH_USER"@"$SSH_HOST_DEV":~/oipa-query-builder

  test_e2e:
    docker:
      - image: circleci/node:10.13.0-browsers
    parallelism: 2
    working_directory: ~/oipa-query-builder
    steps:
      - attach_workspace:
          at: ~/oipa-query-builder
      # setting this env var to only test on dev server when deployed.
      - run:
          name: Set CYPRESS_BASEURL
          command: |
            echo 'export CYPRESS_BASEURL="app.datastore.dev.nyuki.io"'
      - run:
          name: Run E2E test
          # Here we check if the bash variable is unset, or set to a empty string
          command: |
            if [ -z "${CIRCLE_PULL_REQUEST}" ] && [ "${CIRCLE_BRANCH}" != "develop" ]; then
              yarn cypress run
            else
              yarn cypress run
            fi

# WORKFLOWS
workflows:
  version: 2
  test_build_deploy:
    jobs:
      - checkout_repo
      - build_deploy:
          requires:
            - checkout_repo
      - test_e2e:
          requires:
            - build_deploy
