orbs:
  cypress: cypress-io/cypress@1.13.0
version: 2.1
# todo: move all ip's to env vars
# todo: make zz orb
#   - circleci_path
#   - ssh_target
#   - ssh_path
jobs:
  deploy-test:
    docker:
      - image: circleci/node:12.14.1-stretch-browsers
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/
      - add_ssh_keys:
          name: Add SSH KEY
          fingerprints:
            - "21:ee:e6:3e:a8:11:53:67:a1:b2:fa:b3:ce:0a:21:11"
      - run: yarn install
      - run:
          name: Load environment variables
          command: |
            echo 'export REACT_APP_DOC_FILENAME="$REACT_APP_POSTMAN_FILENAME_STG"' >> $BASH_ENV
            source $BASH_ENV
      - run: yarn build
      - run: eval ssh-agent -s
      - run: sudo apt install rsync
      - run: ssh -o StrictHostKeyChecking=no "$SSH_USER"@"$SSH_HOST_DEV" exit
      - run: rsync -O -ave ssh ~/project/build "$SSH_USER"@"$SSH_HOST_DEV":~/stg-iati-cloud-front
      - run: ssh "$SSH_USER"@"$SSH_HOST_DEV" "./ci_update_front.sh;"

  deploy-staging:
    docker:
      - image: circleci/node:12.14.1-stretch-browsers
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/
      - add_ssh_keys:
          name: Add SSH KEY
          fingerprints:
            - "21:ee:e6:3e:a8:11:53:67:a1:b2:fa:b3:ce:0a:21:11"
      - run: yarn install
      - run:
          name: Load environment variables
          command: |
            echo 'export REACT_APP_DOC_FILENAME="$REACT_APP_POSTMAN_FILENAME_STG"' >> $BASH_ENV
            source $BASH_ENV
      - run: yarn build
      - run: eval ssh-agent -s
      - run: sudo apt install rsync
      - run: ssh -o StrictHostKeyChecking=no "$SSH_USER"@"$SSH_HOST_DEV" exit
      - run: rsync -O -ave ssh ~/project/build "$SSH_USER"@"$SSH_HOST_DEV":~/stg-iati-cloud-front
      - run: ssh "$SSH_USER"@"$SSH_HOST_DEV" "./ci_update_front.sh;"

  deploy-production:
    docker:
      - image: circleci/node:12.14.1-stretch-browsers
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn install
      - run:
          name: Load environment variables
          command: |
            echo 'export REACT_APP_DOC_FILENAME="$REACT_APP_POSTMAN_FILENAME_PROD"' >> $BASH_ENV
            source $BASH_ENV
      - run: yarn build
      - run: eval ssh-agent -s
      - run: sudo apt install rsync
      - run: ssh -o StrictHostKeyChecking=no "$SSH_PROD_USER"@"$SSH_HOST_PROD_1" exit
      - run: rsync -O -ave ssh ~/project/build "$SSH_PROD_USER"@"$SSH_HOST_PROD_1":/home/oipa/oipa-query-builder
      - run: ssh "$SSH_PROD_USER"@"$SSH_HOST_PROD_1" "/home/oipa/ci_update_front.sh;"
      - run: ssh -o StrictHostKeyChecking=no "$SSH_PROD_USER"@"$SSH_HOST_PROD_2" exit
      - run: rsync -O -ave ssh ~/project/build "$SSH_PROD_USER"@"$SSH_HOST_PROD_2":/home/oipa/oipa-query-builder
      - run: ssh "$SSH_PROD_USER"@"$SSH_HOST_PROD_2" "/home/oipa/ci_update_front.sh;"

  release:
    docker:
      - image: circleci/node:12.14.1-stretch-browsers
    working_directory: ~/project
    steps:
      - checkout
      - run: npx semantic-release

workflows:
  build-and-test:
    jobs:
      - cypress/install:
          executor: cypress/base-12-6-0
          yarn: true
          build: CI=false yarn build
      # - cypress/run:
      # executor: cypress/browsers-chrome76
      # browser: chrome
      # requires:
      # - cypress/install
      # start: yarn start
      # wait-on: 'http://localhost:3000'
      # yarn: true
      # record: false
      # parallel: true
      # parallelism: 4
      # group: '4 machines'
      # post-steps:
      # - store_test_results:
      # path: cypress/results
      - deploy-test:
          requires:
            - cypress/install
          filters:
            branches:
              only: feature/
      - deploy-staging:
          requires:
            - cypress/install
          filters:
            branches:
              only: develop
      - deploy-production:
          requires:
            - cypress/install
          filters:
            branches:
              only: master
      - release:
          requires:
            - cypress/install
          filters:
            branches:
              only: master
